#!/bin/bash

dir="$(dirname "$0")"

UTILS="$dir/data/applicaties.list"

# Install preferred utilities using the list of packages 'data/utilities.list'
function utilities {
    if (eval `resize` && whiptail --title \
        "Voorkeur Systeem applicaties"  --yesno \
        "Huidige lijst met Voorkeur systeem applicaties: \n\n$(cat $UTILS) \n\nDoor gaan met installatie?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info 'Installeren...'
        show_warning 'Vereist root rechten'
        sudo apt-get install -y --no-install-recommends $(cat $UTILS)
        # Done
        show_success 'Voltooid.'
        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            # Already installed
            show_success 'Is al geinstalleerd.'
            whiptail --title "Voltooid" --msgbox "U Voorkeur systeem applicaties zijn geinstalleerd." 8 78
            main
        else
            whiptail --title "Voltooid" --msgbox "Installatie Voltooid." 8 78
            main
        fi
    else
        main
    fi
}
