#!/bin/bash

# Install Ubuntu Restricted Extras
function codecs {
    # Variables
    PACKAGE=ubuntu-restricted-extras
    NAME="Multimedia Codecs"
    # Check if already installed
    show_info 'Comtroleer of het pakket al aanwezig is..'
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "installatie oké geinstalleerd")
    if [ "" == "$PKGCHECK" ]; then
        show_info $NAME 'Pakket is niet geinstalleerd. Doorgaan'
        if (whiptail --title "Multimedia Codecs" --yesno "Installeer Ubuntu Multimedia Extras voor mhet afspelen van multimedia?" 10 60) then
            # Install
            show_info 'Installeren...'
            show_warning 'Vereist root rechten'
            sudo apt-get install -y ubuntu-restricted-extras
            # Klaar
            show_success 'Klaar.'
        else
            main
        fi
    else
        # Is al geinstalleerd
        show_success 'Pakket is al geinstalleerd.'
        whiptail --title "Voltooid" --msgbox "$NAME zijn geinstalleerd." 8 78
        main
    fi
}
