#!/bin/bash

dir="$(dirname "$0")"

FAVS="$dir/data/favs.list"

# Install preferred applications using the list of packages 'data/favs.list'
function favs {
    if (eval `resize` && whiptail \
        --title "Voorkeur Applicatie's" \
        --yesno "Huidige lijst van voorkeur applicatie's om te installeren: \n\n$(cat $FAVS) \n\nDoorgaan met installatie?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then
        show_info 'Installeren...'
        show_warning 'Vereist root rechten'
        sudo apt-get install -y --no-install-recommends $(cat $FAVS)
        # Done
        show_success 'Voltooid.'
        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            # Already installed
            show_success 'Pakket is al geinstalleerd.'
            whiptail --title "Voltooid" --msgbox "De voorkeur applicaties zijn installeerd." 8 78
            main
        else
            whiptail --title "Voltooid" --msgbox "Installatie compleet." 8 78
            main
        fi
    else
        main
    fi
}
