#!/bin/bash

dir="$(dirname "$0")"

DEVTOOLS="$dir/data/development.list"

# Install preferred development applications using the list of packages 'data/development.list'
function development {
    if (eval `resize` && whiptail \
        --title "Voorkeur Ontwikkellings Applicatie" \
        --yesno "Huidige lijst met voorkeur ontwikkellings hulpmiddelen om te installeren: \n\n$(cat $DEVTOOLS) \n\nDoor gaan met installatie?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then
        show_info 'Installeren...'
        show_warning 'Vereits root rechten'
        sudo apt-get install -y $(cat $DEVTOOLS)
        # Done
        show_success 'Klaar.'
        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            # Already installed
            show_success 'Is al geinstalleerd.'
            whiptail --title "Finished" --msgbox "Your preferred development tools are installed." 8 78
            main
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            main
        fi
    else
        main
    fi
}
